name: MHCPhotography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5264
title: 'Automotive Photographer & Filmmaker'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e7e7e8'
    - '#f1ec3e'
    - '#969326'
    - '#525115'
  brandStrength: 1
  lightness: 0.9375
  saturation: 1
  rhythmicContrast: 1
purpose: []
