name: MHCPhotography
favicon: null
layout_spectrum: 0.59827
typography_spectrum: 0.59447
title: 'Mike Cutler // Automotive Photographer & Filmmaker'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e7e7e8'
    - '#f1ec3e'
    - '#969326'
    - '#525115'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
